// <auto-generated />
using System;
using BlogAndShop.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlogAndShop.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211028065556_InitialConfig")]
    partial class InitialConfig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BlogAndShop.Data.Data.ApplicationRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("BlogAndShop.Data.Data.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("BlogAndShop.Data.Data.BaseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("BaseEntity");

                    b.HasDiscriminator<string>("Discriminator").HasValue("BaseEntity");
                });

            modelBuilder.Entity("BlogAndShop.Data.Data.Post_PostGroup", b =>
                {
                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.HasKey("PostId");

                    b.HasIndex("GroupId");

                    b.ToTable("Post_PostGroup");
                });

            modelBuilder.Entity("BlogAndShop.Data.Data.Post_Tags", b =>
                {
                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("PostId");

                    b.HasIndex("TagId");

                    b.ToTable("Post_Tags");
                });

            modelBuilder.Entity("BlogAndShop.Data.Data.ProductMedia", b =>
                {
                    b.Property<int>("MediaId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("MediaId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductMedia");
                });

            modelBuilder.Entity("BlogAndShop.Data.Data.ProductTag", b =>
                {
                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("TagId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductTag");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("BlogAndShop.Data.Data.Address", b =>
                {
                    b.HasBaseType("BlogAndShop.Data.Data.BaseEntity");

                    b.Property<string>("Alley")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<string>("SecondaryStreet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("OwnerId");

                    b.HasDiscriminator().HasValue("Address");
                });

            modelBuilder.Entity("BlogAndShop.Data.Data.CartItem", b =>
                {
                    b.HasBaseType("BlogAndShop.Data.Data.BaseEntity");

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.HasDiscriminator().HasValue("CartItem");
                });

            modelBuilder.Entity("BlogAndShop.Data.Data.ForumComment", b =>
                {
                    b.HasBaseType("BlogAndShop.Data.Data.BaseEntity");

                    b.Property<int>("ForumId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("bit");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasIndex("ForumId");

                    b.HasIndex("UserId");

                    b.HasDiscriminator().HasValue("ForumComment");
                });

            modelBuilder.Entity("BlogAndShop.Data.Data.ForumTitle", b =>
                {
                    b.HasBaseType("BlogAndShop.Data.Data.BaseEntity");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Keywords")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MetaDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int")
                        .HasColumnName("ForumTitle_OwnerId");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("OwnerId");

                    b.HasDiscriminator().HasValue("ForumTitle");
                });

            modelBuilder.Entity("BlogAndShop.Data.Data.Media", b =>
                {
                    b.HasBaseType("BlogAndShop.Data.Data.BaseEntity");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Media_Description");

                    b.Property<string>("Extension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Media_Title");

                    b.HasDiscriminator().HasValue("Media");
                });

            modelBuilder.Entity("BlogAndShop.Data.Data.Payment", b =>
                {
                    b.HasBaseType("BlogAndShop.Data.Data.BaseEntity");

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FinalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OffAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int")
                        .HasColumnName("Payment_OwnerId");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Payment_Status");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Payment_Text");

                    b.HasIndex("AddressId");

                    b.HasIndex("OwnerId");

                    b.HasDiscriminator().HasValue("Payment");
                });

            modelBuilder.Entity("BlogAndShop.Data.Data.PaymentItem", b =>
                {
                    b.HasBaseType("BlogAndShop.Data.Data.BaseEntity");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PaymentItem_Amount");

                    b.Property<decimal>("OffAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PaymentItem_OffAmount");

                    b.Property<int>("PaymentId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("PaymentItem_ProductId");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("PaymentItem_Quantity");

                    b.HasIndex("PaymentId");

                    b.HasIndex("ProductId");

                    b.HasDiscriminator().HasValue("PaymentItem");
                });

            modelBuilder.Entity("BlogAndShop.Data.Data.PaymentLog", b =>
                {
                    b.HasBaseType("BlogAndShop.Data.Data.BaseEntity");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PaymentLog_Description");

                    b.Property<int>("PaymentId")
                        .HasColumnType("int")
                        .HasColumnName("PaymentLog_PaymentId");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("PaymentLog_Status");

                    b.HasIndex("PaymentId");

                    b.HasDiscriminator().HasValue("PaymentLog");
                });

            modelBuilder.Entity("BlogAndShop.Data.Data.Post", b =>
                {
                    b.HasBaseType("BlogAndShop.Data.Data.BaseEntity");

                    b.Property<string>("BannerImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Post_Description");

                    b.Property<string>("HtmlContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Keywords")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Post_Keywords");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int")
                        .HasColumnName("Post_OwnerId");

                    b.Property<string>("PreferUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Post_Title");

                    b.HasIndex("OwnerId");

                    b.HasDiscriminator().HasValue("Post");
                });

            modelBuilder.Entity("BlogAndShop.Data.Data.PostComment", b =>
                {
                    b.HasBaseType("BlogAndShop.Data.Data.BaseEntity");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("bit")
                        .HasColumnName("PostComment_IsAccepted");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int")
                        .HasColumnName("PostComment_OwnerId");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PostComment_Text");

                    b.HasIndex("OwnerId");

                    b.HasIndex("ParentId");

                    b.HasIndex("PostId");

                    b.HasDiscriminator().HasValue("PostComment");
                });

            modelBuilder.Entity("BlogAndShop.Data.Data.PostGroup", b =>
                {
                    b.HasBaseType("BlogAndShop.Data.Data.BaseEntity");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PostGroup_Description");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PostGroup_Title");

                    b.HasDiscriminator().HasValue("PostGroup");
                });

            modelBuilder.Entity("BlogAndShop.Data.Data.Product", b =>
                {
                    b.HasBaseType("BlogAndShop.Data.Data.BaseEntity");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("BannerImage")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Product_BannerImage");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Product_Description");

                    b.Property<string>("MetaDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Product_MetaDescription");

                    b.Property<decimal>("OffPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductGroupId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("Product_Quantity");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Product_Title");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ProductGroupId");

                    b.HasDiscriminator().HasValue("Product");
                });

            modelBuilder.Entity("BlogAndShop.Data.Data.ProductComment", b =>
                {
                    b.HasBaseType("BlogAndShop.Data.Data.BaseEntity");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("bit")
                        .HasColumnName("ProductComment_IsAccepted");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int")
                        .HasColumnName("ProductComment_OwnerId");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("ProductComment_ParentId");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("ProductComment_ProductId");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ProductComment_Text");

                    b.HasIndex("OwnerId");

                    b.HasIndex("ParentId");

                    b.HasIndex("ProductId");

                    b.HasDiscriminator().HasValue("ProductComment");
                });

            modelBuilder.Entity("BlogAndShop.Data.Data.ProductGroup", b =>
                {
                    b.HasBaseType("BlogAndShop.Data.Data.BaseEntity");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ProductGroup_Description");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("ProductGroup_ParentId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ProductGroup_Title");

                    b.HasIndex("ParentId");

                    b.HasDiscriminator().HasValue("ProductGroup");
                });

            modelBuilder.Entity("BlogAndShop.Data.Data.RoleAccess", b =>
                {
                    b.HasBaseType("BlogAndShop.Data.Data.BaseEntity");

                    b.Property<string>("AttrName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasIndex("RoleId");

                    b.HasDiscriminator().HasValue("RoleAccess");
                });

            modelBuilder.Entity("BlogAndShop.Data.Data.SiteConfig", b =>
                {
                    b.HasBaseType("BlogAndShop.Data.Data.BaseEntity");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SiteConfig_Description");

                    b.Property<string>("LogoFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SiteConfig_Title");

                    b.HasDiscriminator().HasValue("SiteConfig");
                });

            modelBuilder.Entity("BlogAndShop.Data.Data.Tag", b =>
                {
                    b.HasBaseType("BlogAndShop.Data.Data.BaseEntity");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Tag_Description");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int")
                        .HasColumnName("Tag_OwnerId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Tag_Title");

                    b.HasIndex("OwnerId");

                    b.HasDiscriminator().HasValue("Tag");
                });

            modelBuilder.Entity("BlogAndShop.Data.Data.UserCart", b =>
                {
                    b.HasBaseType("BlogAndShop.Data.Data.BaseEntity");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int")
                        .HasColumnName("UserCart_OwnerId");

                    b.HasIndex("OwnerId");

                    b.HasDiscriminator().HasValue("UserCart");
                });

            modelBuilder.Entity("BlogAndShop.Data.Data.Post_PostGroup", b =>
                {
                    b.HasOne("BlogAndShop.Data.Data.PostGroup", "PostGroup")
                        .WithMany("Post_PostGroups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BlogAndShop.Data.Data.Post", "Post")
                        .WithMany("Post_PostGroups")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("PostGroup");
                });

            modelBuilder.Entity("BlogAndShop.Data.Data.Post_Tags", b =>
                {
                    b.HasOne("BlogAndShop.Data.Data.Post", "Post")
                        .WithMany("Post_Tags")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BlogAndShop.Data.Data.Tag", "Tag")
                        .WithMany("Post_Tags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("BlogAndShop.Data.Data.ProductMedia", b =>
                {
                    b.HasOne("BlogAndShop.Data.Data.Media", "Media")
                        .WithMany("ProductMedias")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BlogAndShop.Data.Data.Product", "Product")
                        .WithMany("ProductMedias")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Media");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BlogAndShop.Data.Data.ProductTag", b =>
                {
                    b.HasOne("BlogAndShop.Data.Data.Product", "Product")
                        .WithMany("ProductTags")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BlogAndShop.Data.Data.Tag", "Tag")
                        .WithMany("ProductTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("BlogAndShop.Data.Data.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("BlogAndShop.Data.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("BlogAndShop.Data.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("BlogAndShop.Data.Data.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BlogAndShop.Data.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("BlogAndShop.Data.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BlogAndShop.Data.Data.Address", b =>
                {
                    b.HasOne("BlogAndShop.Data.Data.ApplicationUser", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BlogAndShop.Data.Data.CartItem", b =>
                {
                    b.HasOne("BlogAndShop.Data.Data.UserCart", "UserCart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BlogAndShop.Data.Data.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("UserCart");
                });

            modelBuilder.Entity("BlogAndShop.Data.Data.ForumComment", b =>
                {
                    b.HasOne("BlogAndShop.Data.Data.ForumTitle", "ForumTitle")
                        .WithMany("ForumComments")
                        .HasForeignKey("ForumId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BlogAndShop.Data.Data.ApplicationUser", "User")
                        .WithMany("ForumComments")
                        .HasForeignKey("UserId");

                    b.Navigation("ForumTitle");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BlogAndShop.Data.Data.ForumTitle", b =>
                {
                    b.HasOne("BlogAndShop.Data.Data.ApplicationUser", "User")
                        .WithMany("ForumTitles")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BlogAndShop.Data.Data.Payment", b =>
                {
                    b.HasOne("BlogAndShop.Data.Data.Address", "Address")
                        .WithMany("Payments")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BlogAndShop.Data.Data.ApplicationUser", "User")
                        .WithMany("Payments")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BlogAndShop.Data.Data.PaymentItem", b =>
                {
                    b.HasOne("BlogAndShop.Data.Data.Payment", "Payment")
                        .WithMany("PaymentItems")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BlogAndShop.Data.Data.Product", "Product")
                        .WithMany("PaymentItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Payment");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BlogAndShop.Data.Data.PaymentLog", b =>
                {
                    b.HasOne("BlogAndShop.Data.Data.Payment", "Payment")
                        .WithMany("PaymentLogs")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("BlogAndShop.Data.Data.Post", b =>
                {
                    b.HasOne("BlogAndShop.Data.Data.ApplicationUser", "User")
                        .WithMany("Posts")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BlogAndShop.Data.Data.PostComment", b =>
                {
                    b.HasOne("BlogAndShop.Data.Data.ApplicationUser", "User")
                        .WithMany("PostComments")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BlogAndShop.Data.Data.PostComment", "ParentPostComment")
                        .WithMany("PostComments")
                        .HasForeignKey("ParentId");

                    b.HasOne("BlogAndShop.Data.Data.Post", "Post")
                        .WithMany("PostComments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ParentPostComment");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BlogAndShop.Data.Data.Product", b =>
                {
                    b.HasOne("BlogAndShop.Data.Data.ApplicationUser", "User")
                        .WithMany("Products")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BlogAndShop.Data.Data.ProductGroup", "ProductGroup")
                        .WithMany("Products")
                        .HasForeignKey("ProductGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductGroup");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BlogAndShop.Data.Data.ProductComment", b =>
                {
                    b.HasOne("BlogAndShop.Data.Data.ApplicationUser", "Owner")
                        .WithMany("ProductComments")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BlogAndShop.Data.Data.ProductComment", "ParentProductComment")
                        .WithMany("ProductComments")
                        .HasForeignKey("ParentId");

                    b.HasOne("BlogAndShop.Data.Data.Product", "Product")
                        .WithMany("ProductComments")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("ParentProductComment");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BlogAndShop.Data.Data.ProductGroup", b =>
                {
                    b.HasOne("BlogAndShop.Data.Data.ProductGroup", "ParentProductGroup")
                        .WithMany("ProductGroups")
                        .HasForeignKey("ParentId");

                    b.Navigation("ParentProductGroup");
                });

            modelBuilder.Entity("BlogAndShop.Data.Data.RoleAccess", b =>
                {
                    b.HasOne("BlogAndShop.Data.Data.ApplicationRole", "ApplicationRole")
                        .WithMany("RoleAccesses")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationRole");
                });

            modelBuilder.Entity("BlogAndShop.Data.Data.Tag", b =>
                {
                    b.HasOne("BlogAndShop.Data.Data.ApplicationUser", "User")
                        .WithMany("Tags")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BlogAndShop.Data.Data.UserCart", b =>
                {
                    b.HasOne("BlogAndShop.Data.Data.ApplicationUser", "User")
                        .WithMany("UserCarts")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BlogAndShop.Data.Data.ApplicationRole", b =>
                {
                    b.Navigation("RoleAccesses");
                });

            modelBuilder.Entity("BlogAndShop.Data.Data.ApplicationUser", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("ForumComments");

                    b.Navigation("ForumTitles");

                    b.Navigation("Payments");

                    b.Navigation("PostComments");

                    b.Navigation("Posts");

                    b.Navigation("ProductComments");

                    b.Navigation("Products");

                    b.Navigation("Tags");

                    b.Navigation("UserCarts");
                });

            modelBuilder.Entity("BlogAndShop.Data.Data.Address", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("BlogAndShop.Data.Data.ForumTitle", b =>
                {
                    b.Navigation("ForumComments");
                });

            modelBuilder.Entity("BlogAndShop.Data.Data.Media", b =>
                {
                    b.Navigation("ProductMedias");
                });

            modelBuilder.Entity("BlogAndShop.Data.Data.Payment", b =>
                {
                    b.Navigation("PaymentItems");

                    b.Navigation("PaymentLogs");
                });

            modelBuilder.Entity("BlogAndShop.Data.Data.Post", b =>
                {
                    b.Navigation("Post_PostGroups");

                    b.Navigation("Post_Tags");

                    b.Navigation("PostComments");
                });

            modelBuilder.Entity("BlogAndShop.Data.Data.PostComment", b =>
                {
                    b.Navigation("PostComments");
                });

            modelBuilder.Entity("BlogAndShop.Data.Data.PostGroup", b =>
                {
                    b.Navigation("Post_PostGroups");
                });

            modelBuilder.Entity("BlogAndShop.Data.Data.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("PaymentItems");

                    b.Navigation("ProductComments");

                    b.Navigation("ProductMedias");

                    b.Navigation("ProductTags");
                });

            modelBuilder.Entity("BlogAndShop.Data.Data.ProductComment", b =>
                {
                    b.Navigation("ProductComments");
                });

            modelBuilder.Entity("BlogAndShop.Data.Data.ProductGroup", b =>
                {
                    b.Navigation("ProductGroups");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("BlogAndShop.Data.Data.Tag", b =>
                {
                    b.Navigation("Post_Tags");

                    b.Navigation("ProductTags");
                });

            modelBuilder.Entity("BlogAndShop.Data.Data.UserCart", b =>
                {
                    b.Navigation("CartItems");
                });
#pragma warning restore 612, 618
        }
    }
}
